# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: waka.cloudis::lang.controllers.biblios.label

# Model Form Field configuration
form: $/waka/cloudis/models/biblio/fields.yaml

# Model Class name
modelClass: Waka\Cloudis\Models\Biblio

# Default redirect location
defaultRedirect: waka/cloudis/biblios

# Create page
create:
    title: backend::lang.form.create_title
    redirect: waka/cloudis/biblios/update/:id
    redirectClose: waka/cloudis/biblios

# Update page
update:
    title: backend::lang.form.update_title
    redirect: waka/cloudis/biblios/update/:id
    redirectClose: waka/cloudis/biblios

# Preview page
preview:
    title: backend::lang.form.preview_title
